import { createInstance } from "i18next"
import { initReactI18next } from "react-i18next"

export type AppLanguagePreference = "zh-CN" | "en"
export type AppLocale = AppLanguagePreference

export const appLanguageStorageKey = "convax.desktop.app-language.v1"

interface AppLanguageStorage {
  getItem(key: string): string | null
  setItem(key: string, value: string): void
}

const languagePreferences: readonly AppLanguagePreference[] = ["zh-CN", "en"]

export function readAppLanguagePreference(storage: Pick<AppLanguageStorage, "getItem">): AppLanguagePreference {
  try {
    const value = JSON.parse(storage.getItem(appLanguageStorageKey) ?? "null") as unknown
    if (!value || typeof value !== "object") return "en"
    const candidate = value as { language?: unknown; version?: unknown }
    if (candidate.version !== 1 || !languagePreferences.includes(candidate.language as AppLanguagePreference))
      return "en"
    return candidate.language as AppLanguagePreference
  } catch {
    return "en"
  }
}

export function writeAppLanguagePreference(
  storage: Pick<AppLanguageStorage, "setItem">,
  language: AppLanguagePreference,
) {
  try {
    storage.setItem(appLanguageStorageKey, JSON.stringify({ language, version: 1 }))
    return true
  } catch {
    return false
  }
}

export function resolveAppLocale(preference: AppLanguagePreference): AppLocale {
  return preference
}

const englishMessages = {
  "appMenu.capabilities": "Skill & Plugin",
  "appMenu.localWorkspace": "Local workspace",
  "appMenu.localWorkspaceDescription": "Settings are stored on this device",
  "appMenu.open": "Open application menu",
  "appMenu.services": "Services",
  "appMenu.settings": "Settings",
  "capabilities.agentSkill": "Agent Skill",
  "capabilities.agentMcpClientSetup": "OAuth client setup is required before this Agent Plugin can connect.",
  "capabilities.agentMcpConnected": "Account connected.",
  "capabilities.agentMcpConnectedSkill": "Account connected · {skill} workflow is ready.",
  "capabilities.agentMcpDisabled": "This Agent connection is disabled.",
  "capabilities.agentMcpFailed": "The Agent connection needs attention. Reconnect before using this Plugin.",
  "capabilities.agentMcpNeedsConnection": "Connect an account, then use this Plugin from the Agent panel.",
  "capabilities.agentMcpUnavailable": "The Agent connection status is unavailable. Try reconnecting.",
  "capabilities.availableSkills": "Installed & discovered Skills",
  "capabilities.close": "Close capability center",
  "capabilities.closeSkillDetails": "Close Skill details",
  "capabilities.connectPlugin": "Connect",
  "capabilities.connectingPlugin": "Connecting…",
  "capabilities.copied": "Copied",
  "capabilities.copy": "Copy",
  "capabilities.description": "Extend Agent workflows and Canvas experiences",
  "capabilities.downloadBreakdown": "Plugin {packageSize} · Companion {companionSize}",
  "capabilities.downloadSize": "Download {size}",
  "capabilities.globalReadOnly": "Global · read only",
  "capabilities.globalThisDevice": "Global · this device",
  "capabilities.githubRelease": "GitHub Release",
  "capabilities.importPlugin": "Import Plugin",
  "capabilities.importSkill": "Import Skill",
  "capabilities.importedPlugins": "Imported Plugins",
  "capabilities.includedSkills": "Skill marketplace",
  "capabilities.installCompanionSkill": "Install companion Skill",
  "capabilities.installPlugin": "Install Plugin",
  "capabilities.installProvidingPlugin": "Install providing Plugin",
  "capabilities.installToolConsent": "Installing authorizes the local tool {command} to run on this device.",
  "capabilities.installSkill": "Install Skill",
  "capabilities.installed": "Installed",
  "capabilities.installedVersion": "Installed v{version}",
  "capabilities.loading": "Loading capabilities…",
  "capabilities.loadingSkillDetails": "Loading Skill files…",
  "capabilities.managed": "Managed",
  "capabilities.noCatalogPlugins": "The local Plugin catalog is empty.",
  "capabilities.noIncludedSkills": "The Skill marketplace is empty.",
  "capabilities.noSkills": "No installed or globally discovered Skills were found.",
  "capabilities.noTextPreview": "This file is binary, so a text preview is not available.",
  "capabilities.openCanvasToUsePlugin": "Open or create a Canvas before adding this Plugin.",
  "capabilities.openProjectToUseAgent": "Open a Project before using this Plugin in Agent.",
  "capabilities.plugins": "Plugin",
  "capabilities.pluginsDescription":
    "Plugins add sandboxed Canvas experiences, tools, services, and owned Skills. Owned Skills are installed and removed together with their Plugin.",
  "capabilities.pluginInstalled": "Plugin installed",
  "capabilities.pluginReady": "Ready to add {name} to the current Canvas.",
  "capabilities.pluginCatalog": "Plugin catalog",
  "capabilities.providedByPlugin": "Provided by {name}",
  "capabilities.reconnectPlugin": "Reconnect",
  "capabilities.retry": "Retry",
  "capabilities.skills": "Skill",
  "capabilities.skillsDescription":
    "Skills are portable Agent workflows. Standalone Skills are managed here; Plugin-provided Skills follow their owning Plugin's lifecycle.",
  "capabilities.skillFiles": "Skill files",
  "capabilities.skillPreview": "Preview",
  "capabilities.title": "Skill & Plugin",
  "capabilities.unavailable": "Capabilities are not available.",
  "capabilities.uninstall": "Uninstall",
  "capabilities.updateAvailable": "Update available",
  "capabilities.updatePlugin": "Update Plugin",
  "capabilities.useOnCanvas": "Add to Canvas",
  "capabilities.useInAgent": "Use in Agent",
  "capabilities.viewDetails": "View details",
  "settings.back": "Back to app",
  "settings.capabilities": "Skill & Plugin",
  "settings.general": "General",
  "settings.language": "Language",
  "settings.language.en": "English",
  "settings.language.zhCN": "简体中文",
  "settings.languageDescription": "Choose the language used by the Convax desktop interface.",
  "settings.localDescription": "Preferences for this local Convax workspace",
  "settings.services": "Services",
  "settings.title": "Settings",
  "pets.title": "Pets",
  "services.account": "Account",
  "services.actions": "Service actions",
  "services.attention": "Needs attention",
  "services.authenticated": "Authenticated",
  "services.authentication": "Authentication",
  "services.authNotApplicable": "Not required",
  "services.authRequired": "Required",
  "services.authorizationUnavailable": "This Plugin does not provide in-app authorization.",
  "services.billing": "Billing",
  "services.cancelAuthorization": "Cancel authorization",
  "services.catalog": "Available services",
  "services.capabilities": "Capabilities",
  "services.capability.audio": "Audio",
  "services.capability.image": "Image",
  "services.capability.llm": "LLM",
  "services.capability.text": "Text",
  "services.capability.video": "Video",
  "services.configure": "Configure",
  "services.connectionDetails": "Connection",
  "services.connected": "Connected",
  "services.consumed": "{value} {unit} used{period}",
  "services.credential": "Credential",
  "services.credits": "Credits",
  "services.defaultModel": "Default",
  "services.description": "Capabilities, models, accounts, and usage from built-in and installed services",
  "services.disconnected": "Disconnected",
  "services.empty": "No installed Plugin contributes a service.",
  "services.failed": "Verification failed",
  "services.free": "Free",
  "services.install": "Install services",
  "services.interval.month": "monthly",
  "services.interval.year": "yearly",
  "services.loading": "Loading services…",
  "services.loadingModels": "Loading models…",
  "services.loadingStatus": "Checking service status…",
  "services.inventorySummary": "{services} services · {models} models",
  "services.modelListLabel": "Model results",
  "services.modelCount": "{count} models",
  "services.modelResultCount": "{count} results",
  "services.modelResultsLimited": "Showing the first {shown} of {total} models. Search to narrow the list.",
  "services.models": "Models",
  "services.noModelMatches": "No models match this search.",
  "services.noModels": "No available models reported.",
  "services.notConfigured": "Not configured",
  "services.noSubscription": "No active subscription",
  "services.openCodeDescription": "The built-in OpenCode LLM runtime and its currently connected model catalog.",
  "services.reconfigure": "Reconfigure",
  "services.plan": "Plan",
  "services.remaining": "{value} {unit} remaining",
  "services.retry": "Refresh",
  "services.searchModels": "Search models",
  "services.searchModelsPlaceholder": "Search models or providers",
  "services.signOut": "Sign out",
  "services.signOutCancel": "Cancel",
  "services.signOutConfirm": "Sign out and remove this Plugin's local credential?",
  "services.signOutConfirmAction": "Sign out",
  "services.subscription": "Subscription",
  "services.subscriptionStatus": "Subscription status",
  "services.title": "Services",
  "services.unavailable": "Unavailable",
  "services.unavailableData": "Not supported or unavailable",
  "services.unknown": "Unknown",
  "services.unverified": "Configured · not verified",
  "services.usage": "Usage",
  "services.upgrade": "Upgrade to {plan}",
  "services.checkoutPending": "Checkout for {plan} is {status}. Complete it in your browser, then refresh.",
  "services.checkoutStatus.converted": "complete",
  "services.checkoutStatus.created": "ready",
  "services.checkoutStatus.expired": "expired",
  "services.checkoutStatus.failed": "failed",
  "services.checkoutStatus.processing": "processing",
  "services.verified": "Configured · verified",
  "services.version": "v{version}",
} as const

export type AppMessageKey = keyof typeof englishMessages

const chineseMessages = {
  "appMenu.capabilities": "技能与插件",
  "appMenu.localWorkspace": "本地工作区",
  "appMenu.localWorkspaceDescription": "设置保存在这台设备上",
  "appMenu.open": "打开应用菜单",
  "appMenu.services": "服务",
  "appMenu.settings": "设置",
  "capabilities.agentSkill": "智能体技能",
  "capabilities.agentMcpClientSetup": "此 Agent 插件还需要 OAuth 客户端配置，暂时无法连接。",
  "capabilities.agentMcpConnected": "账号已连接。",
  "capabilities.agentMcpConnectedSkill": "账号已连接 · {skill} 工作流已就绪。",
  "capabilities.agentMcpDisabled": "此 Agent 连接已被禁用。",
  "capabilities.agentMcpFailed": "Agent 连接需要处理，请重新连接后再使用此插件。",
  "capabilities.agentMcpNeedsConnection": "先连接账号，然后在 Agent 面板中使用此插件。",
  "capabilities.agentMcpUnavailable": "暂时无法获取 Agent 连接状态，请尝试重新连接。",
  "capabilities.availableSkills": "已安装与已发现技能",
  "capabilities.close": "关闭技能与插件",
  "capabilities.closeSkillDetails": "关闭技能详情",
  "capabilities.connectPlugin": "连接账号",
  "capabilities.connectingPlugin": "连接中…",
  "capabilities.copied": "已复制",
  "capabilities.copy": "复制",
  "capabilities.description": "扩展 Agent 工作流和画布体验",
  "capabilities.downloadBreakdown": "插件 {packageSize} · 运行组件 {companionSize}",
  "capabilities.downloadSize": "下载 {size}",
  "capabilities.globalReadOnly": "全局 · 只读",
  "capabilities.globalThisDevice": "全局 · 当前设备",
  "capabilities.githubRelease": "GitHub 发布页",
  "capabilities.importPlugin": "导入插件",
  "capabilities.importSkill": "导入技能",
  "capabilities.importedPlugins": "已导入插件",
  "capabilities.includedSkills": "技能市场",
  "capabilities.installCompanionSkill": "安装配套技能",
  "capabilities.installPlugin": "安装插件",
  "capabilities.installProvidingPlugin": "安装提供此技能的插件",
  "capabilities.installToolConsent": "安装即授权本地工具 {command} 在本机运行。",
  "capabilities.installSkill": "安装技能",
  "capabilities.installed": "已安装",
  "capabilities.installedVersion": "已安装 v{version}",
  "capabilities.loading": "正在加载技能与插件…",
  "capabilities.loadingSkillDetails": "正在加载技能文件…",
  "capabilities.managed": "由 Convax 管理",
  "capabilities.noCatalogPlugins": "本地插件目录为空。",
  "capabilities.noIncludedSkills": "技能市场当前为空。",
  "capabilities.noSkills": "未发现已安装或全局可用的技能。",
  "capabilities.noTextPreview": "这是二进制文件，无法提供文本预览。",
  "capabilities.openCanvasToUsePlugin": "请先打开或创建一个画布，再添加此插件。",
  "capabilities.openProjectToUseAgent": "请先打开一个项目，再在 Agent 中使用此插件。",
  "capabilities.plugins": "插件",
  "capabilities.pluginsDescription":
    "插件可扩展沙箱化画布体验、工具、服务和自带技能；插件自带技能会随插件一起安装和卸载。",
  "capabilities.pluginInstalled": "插件已安装",
  "capabilities.pluginReady": "已可将 {name} 添加到当前画布。",
  "capabilities.pluginCatalog": "插件目录",
  "capabilities.providedByPlugin": "由 {name} 提供",
  "capabilities.reconnectPlugin": "重新连接",
  "capabilities.retry": "重试",
  "capabilities.skills": "技能",
  "capabilities.skillsDescription":
    "技能是可移植的 Agent 工作流。独立技能可在这里管理，插件提供的技能则跟随所属插件的生命周期。",
  "capabilities.skillFiles": "技能文件",
  "capabilities.skillPreview": "内容预览",
  "capabilities.title": "技能与插件",
  "capabilities.unavailable": "技能与插件当前不可用。",
  "capabilities.uninstall": "卸载",
  "capabilities.updateAvailable": "有可用更新",
  "capabilities.updatePlugin": "更新插件",
  "capabilities.useOnCanvas": "添加到画布",
  "capabilities.useInAgent": "在 Agent 中使用",
  "capabilities.viewDetails": "查看详情",
  "settings.back": "返回应用",
  "settings.capabilities": "技能与插件",
  "settings.general": "常规",
  "settings.language": "语言",
  "settings.language.en": "English",
  "settings.language.zhCN": "简体中文",
  "settings.languageDescription": "选择 Convax 桌面界面使用的语言。",
  "settings.localDescription": "当前本地 Convax 工作区的全局偏好",
  "settings.services": "服务",
  "settings.title": "设置",
  "pets.title": "宠物",
  "services.account": "账号",
  "services.actions": "服务操作",
  "services.attention": "需要处理",
  "services.authenticated": "已授权",
  "services.authentication": "授权",
  "services.authNotApplicable": "无需授权",
  "services.authRequired": "需要授权",
  "services.authorizationUnavailable": "该插件未提供应用内授权能力。",
  "services.billing": "计费方式",
  "services.cancelAuthorization": "取消授权",
  "services.catalog": "可用服务",
  "services.capabilities": "提供能力",
  "services.capability.audio": "音频",
  "services.capability.image": "生图",
  "services.capability.llm": "LLM",
  "services.capability.text": "文本",
  "services.capability.video": "生视频",
  "services.configure": "配置",
  "services.connectionDetails": "连接信息",
  "services.connected": "已连接",
  "services.consumed": "已消耗 {value} {unit}{period}",
  "services.credential": "凭证",
  "services.credits": "额度余额",
  "services.defaultModel": "默认",
  "services.description": "查看内置与已安装服务提供的能力、模型、账号和用量",
  "services.disconnected": "未连接",
  "services.empty": "当前没有已安装插件提供服务。",
  "services.failed": "验证失败",
  "services.free": "免费",
  "services.install": "安装服务",
  "services.interval.month": "月付",
  "services.interval.year": "年付",
  "services.loading": "正在加载服务…",
  "services.loadingModels": "正在加载模型…",
  "services.loadingStatus": "正在检查服务状态…",
  "services.inventorySummary": "{services} 个服务 · {models} 个模型",
  "services.modelListLabel": "模型搜索结果",
  "services.modelCount": "{count} 个模型",
  "services.modelResultCount": "{count} 个结果",
  "services.modelResultsLimited": "当前显示前 {shown} / {total} 个模型，请搜索以缩小范围。",
  "services.models": "模型列表",
  "services.noModelMatches": "没有匹配的模型。",
  "services.noModels": "当前未报告可用模型。",
  "services.notConfigured": "未配置",
  "services.noSubscription": "暂无有效订阅",
  "services.openCodeDescription": "Convax 内置的 OpenCode LLM 运行时，以及当前已连接的模型目录。",
  "services.reconfigure": "重新配置",
  "services.plan": "套餐",
  "services.remaining": "剩余 {value} {unit}",
  "services.retry": "刷新",
  "services.searchModels": "搜索模型",
  "services.searchModelsPlaceholder": "搜索模型或提供方",
  "services.signOut": "退出授权",
  "services.signOutCancel": "取消",
  "services.signOutConfirm": "确认退出并清除该插件保存在本机的凭证吗？",
  "services.signOutConfirmAction": "确认退出",
  "services.subscription": "订阅",
  "services.subscriptionStatus": "订阅状态",
  "services.title": "服务",
  "services.unavailable": "不可用",
  "services.unavailableData": "不支持或暂不可用",
  "services.unknown": "未知",
  "services.unverified": "已配置 · 未验证",
  "services.usage": "已用额度",
  "services.upgrade": "升级到 {plan}",
  "services.checkoutPending": "{plan} 套餐的升级流程{status}，请在浏览器完成后刷新。",
  "services.checkoutStatus.converted": "已完成",
  "services.checkoutStatus.created": "已就绪",
  "services.checkoutStatus.expired": "已过期",
  "services.checkoutStatus.failed": "失败",
  "services.checkoutStatus.processing": "正在处理",
  "services.verified": "已配置 · 已验证",
  "services.version": "v{version}",
} satisfies Record<AppMessageKey, string>

export const appI18n = createInstance()

void appI18n.use(initReactI18next).init({
  fallbackLng: "en",
  initAsync: false,
  interpolation: {
    escapeValue: false,
    prefix: "{",
    suffix: "}",
  },
  keySeparator: false,
  lng: "en",
  resources: {
    en: { translation: englishMessages },
    "zh-CN": { translation: chineseMessages },
  },
  supportedLngs: languagePreferences,
})

export function changeAppLanguage(locale: AppLocale) {
  return appI18n.changeLanguage(locale)
}

export function appMessage(locale: AppLocale, key: AppMessageKey, values?: Readonly<Record<string, string | number>>) {
  return appI18n.getFixedT(locale)(key, values)
}
