export const COLLABORATION_PROTOCOL_MAJOR = 1 as const
export const CAUSAL_EDIT_KIND_CODE = 1 as const
export const CAUSAL_EDIT_MAGIC = "CVXCOLL" as const
export const CAUSAL_EDIT_PREFIX_BYTES = 88 as const

/**
 * Identity of the one current collaboration protocol. `protocolDigest` is the
 * only protocol identity; it is recomputed from this package's own source data
 * by the current protocol descriptor and must equal this anchor.
 */
export const CURRENT_PROTOCOL_IDENTITIES = Object.freeze({
  protocolDigest: "8295f918e8f7b8297c080db03672fc410542280f639d9b40a8e324e560f07ae9",
  uriProtocolDigest: "9030aecd6902888e5e91532fcc2ec3f1a377e79ae59c092ee80fbbf1a01fac38",
  limitsDigest: "88c018e5289f8b9a359f6ae171aed00885d5fa0913f4a1c36274b35e4cee12f7",
  channelContractDigest: "0fa34e8d93f26e585e6d9baa0ecf0c09a38494d03247b91843e2bca0e93df242",
} as const)

export const PROTOCOL_SCHEMA_ARTIFACTS = Object.freeze([
  Object.freeze({
    artifactDigest: "09d5f8748d91474de45eb3a88fe6d3054adb79e8a44dd311c9024ab95b27250a",
    format: "convax.canvas-protocol-schema",
    name: "canvas-schema",
  }),
  Object.freeze({
    artifactDigest: "1449c229278d0e30ddb800751c025ec546e8e0aea3c1e99215da411e3500a7dc",
    format: "convax.collaboration-kernel-protocol-schema",
    name: "collaboration-kernel",
  }),
  Object.freeze({
    artifactDigest: "ac6605ee974a47be65a02c478e854971cbd54146db147cf943391a0f4f557e45",
    format: "convax.control-plane-protocol-schema",
    name: "control-plane",
  }),
  Object.freeze({
    artifactDigest: "99ebca8cc048f6cf919d55a9829091e2450e59a10b87b5410d9b0243459be37c",
    format: "convax.project-persistence-protocol-schema",
    name: "project-persistence",
  }),
] as const)

export const PROTOCOL_TYPE_NAMESPACES = Object.freeze([
  Object.freeze({ namespace: "canvas-schema", imports: Object.freeze(["collaboration-kernel", "control-plane", "global-uri"] as const) }),
  Object.freeze({ namespace: "collaboration-kernel", imports: Object.freeze(["global-uri"] as const) }),
  Object.freeze({ namespace: "control-plane", imports: Object.freeze(["collaboration-kernel", "global-uri", "project-persistence"] as const) }),
  Object.freeze({ namespace: "global-uri", imports: Object.freeze([] as const) }),
  Object.freeze({ namespace: "project-persistence", imports: Object.freeze(["canvas-schema", "collaboration-kernel", "control-plane", "global-uri"] as const) }),
] as const)

export const YJS_WIRE_CODEC = Object.freeze({
  applyCodec: "Y.applyUpdate",
  format: "convax.yjs-wire-codec",
  package: "yjs",
  packageIntegrity: "sha512-Eq+5BRfbeGyqGVrTJL3bEcr8gKkxPuyuoHmAwpk52fDb8kOVMrfVSTRPd6yiGgX5Fskb96qCRjzjbRjrL4YEnw==",
  stateVectorCodec: "Y.encodeStateVector",
  updateCodec: "Y.encodeStateAsUpdate",
  updateVersion: "v1",
  version: "13.6.31",
} as const)

/**
 * Sorted closed set of domain separators admitted by the current protocol. It is
 * package-owned source data and participates in the current protocol digest.
 */
export const PROTOCOL_DIGEST_DOMAIN_REGISTRY = Object.freeze([
  "convax.active-peer-directory-core",
  "convax.actual-write-evidence",
  "convax.authorization-mutation-core",
  "convax.begin-authorization-epoch-core",
  "convax.blob-durable-ack-core",
  "convax.canonical-state",
  "convax.canvas-actual-write-value",
  "convax.canvas-containment-slot",
  "convax.canvas-creation-group-member-set",
  "convax.canvas-data-register",
  "convax.canvas-derived-id",
  "convax.canvas-edge-identity",
  "convax.canvas-effective-child-set",
  "convax.canvas-effective-data",
  "convax.canvas-effective-plugin",
  "convax.canvas-generation-begin",
  "convax.canvas-generation-dismissal",
  "convax.canvas-generation-lifecycle",
  "convax.canvas-generation-recovery-failure",
  "convax.canvas-generation-terminal",
  "convax.canvas-genesis-core",
  "convax.canvas-geometry",
  "convax.canvas-group-geometry-plan",
  "convax.canvas-history-footprint",
  "convax.canvas-history-material",
  "convax.canvas-history-materialization",
  "convax.canvas-metadata-effective",
  "convax.canvas-metadata-slot",
  "convax.canvas-node-identity",
  "convax.canvas-obstacle-projection",
  "convax.canvas-operation-receipt",
  "convax.canvas-projected-generation",
  "convax.canvas-semantic-guard",
  "convax.canvas-semantic-history-root",
  "convax.canvas-semantic-history-state",
  "convax.causal-context",
  "convax.causal-dependency-set",
  "convax.causal-edit-core",
  "convax.causal-edit-frame-digest",
  "convax.causal-edit-signature",
  "convax.causal-frontier",
  "convax.causal-head-ref",
  "convax.causal-signer-authority",
  "convax.checkpoint-content-certificate",
  "convax.checkpoint-content-certificate-core",
  "convax.checkpoint-validation-carrier-index",
  "convax.collaboration-scope-entry-core",
  "convax.document-registration-abandonment-core",
  "convax.document-registration-claim-core",
  "convax.document-scope",
  "convax.document-shard-reset-approval-core",
  "convax.document-shard-reset-claim-core-digest",
  "convax.document-shard-reset-claim-signature",
  "convax.document-shard-reset-confirmation-core",
  "convax.document-shard-reset-route-cas-core-digest",
  "convax.empty-project-index-genesis-attestation-core",
  "convax.generation-first-loss-receipt-core",
  "convax.local-owner-edit-authorization-core",
  "convax.local-project-store-record-digest",
  "convax.member-credential-core",
  "convax.membership-snapshot-core",
  "convax.mutation-challenge-core",
  "convax.mutation-proof-core",
  "convax.mutation-receipt-core",
  "convax.native-document-store-key",
  "convax.native-object-store-key",
  "convax.owner-actual-write-evidence",
  "convax.owner-canonicalizer-descriptor",
  "convax.peer-channel-contract",
  "convax.peer-channel-open-core",
  "convax.peer-freshness-ticket-core",
  "convax.peer-handshake-core",
  "convax.peer-inventory-page-core",
  "convax.peer-inventory-root-core",
  "convax.peer-message-body",
  "convax.peer-message-core",
  "convax.peer-ticket-request-core",
  "convax.peer-transfer-chunk",
  "convax.peer-transfer-manifest-core",
  "convax.project-admin-capability-core",
  "convax.project-conflict-projection",
  "convax.project-content-family-projection",
  "convax.project-derived-identity",
  "convax.project-entry-location-projection",
  "convax.project-file-projection",
  "convax.project-index-intent-digest",
  "convax.project-index-live-scope-manifest",
  "convax.project-index-record-digest",
  "convax.project-index-write-value",
  "convax.project-reset-approval-core",
  "convax.project-reset-confirmation-core",
  "convax.project-resource-reference-digest",
  "convax.project-route-projection",
  "convax.protocol-limits",
  "convax.protocol-schema-artifact",
  "convax.protocol-schema-bundle-core",
  "convax.prunable-checkpoint-set-certificate",
  "convax.prunable-checkpoint-set-certificate-core",
  "convax.registry-cutoff-coverage-page-core",
  "convax.registry-cutoff-coverage-root-core",
  "convax.registry-entry-identity",
  "convax.registry-entry-set",
  "convax.registry-snapshot-core",
  "convax.replica-actor-credential-core",
  "convax.replica-actor-head-set",
  "convax.replica-actor-id",
  "convax.replica-causal-floor-ack",
  "convax.replica-causal-floor-ack-core",
  "convax.replica-checkpoint",
  "convax.replica-checkpoint-core",
  "convax.replica-durable-ack-core",
  "convax.replica-edit-authorization-core",
  "convax.replica-id-reservation-receipt-core",
  "convax.replica-id-reservation-request-core",
  "convax.replica-project-floor-page-core",
  "convax.replica-project-floor-root-core",
  "convax.service-trust-bundle-core",
  "convax.session-challenge-core",
  "convax.session-credential-core",
  "convax.session-proof-core",
  "convax.stable-checkpoint-set-core",
  "convax.state-vector",
  "convax.target-cutoff-leaf-core",
  "convax.team-epoch-rollover-challenge-core",
  "convax.team-epoch-rollover-proof-core",
  "convax.team-epoch-rollover-receipt-core",
  "convax.typed-intent",
  "convax.validation-artifact-set",
  "convax.yjs-update",
] as const)

export const KERNEL_LIMITS = Object.freeze({
  actualWriteEvidenceJcsBytes: 256 * 1024,
  causalContextJcsBytes: 64 * 1024,
  causalDependencyRefs: 256,
  causalEnvelopeBytes: 2 * 1024 * 1024,
  causalFrontierHeads: 256,
  causalHeaderJcsBytes: 64 * 1024,
  checkpointFrontierHeads: 256,
  checkpointParents: 8,
  checkpointSnapshotBytes: 32 * 1024 * 1024,
  changedPaths: 2_048,
  localOutboxBytesPerDocument: 512 * 1024 * 1024,
  localOutboxFramesPerDocument: 4_096,
  localRecoveryBranchBytes: 1024 * 1024 * 1024,
  oneChangedPathUtf8Bytes: 512,
  pendingInboxBytesPerDocument: 256 * 1024 * 1024,
  pendingInboxBytesPerRemoteActor: 32 * 1024 * 1024,
  pendingInboxFramesPerDocument: 4_096,
  pendingInboxFramesPerRemoteActor: 512,
  quarantineBytesPerProject: 128 * 1024 * 1024,
  quarantineObjectsPerProject: 1_024,
  retainedDurableAcksPerFrame: 32,
  stateVectorBytes: 64 * 1024,
  stableSetCertificates: 8,
  typedIntentJcsBytes: 512 * 1024,
  validationArtifactRefs: 64,
  writes: 2_048,
  yjsUpdateBytes: 1024 * 1024,
} as const)

export const KERNEL_DIGEST_DOMAINS = Object.freeze({
  actualWriteEvidence: "convax.actual-write-evidence",
  canonicalState: "convax.canonical-state",
  causalContext: "convax.causal-context",
  causalDependencySet: "convax.causal-dependency-set",
  causalEditCore: "convax.causal-edit-core",
  causalEditFrameDigest: "convax.causal-edit-frame-digest",
  causalEditSignature: "convax.causal-edit-signature",
  causalFrontier: "convax.causal-frontier",
  causalHeadRef: "convax.causal-head-ref",
  causalSignerAuthority: "convax.causal-signer-authority",
  checkpointContentCertificateCore: "convax.checkpoint-content-certificate-core",
  checkpointContentCertificate: "convax.checkpoint-content-certificate",
  documentScope: "convax.document-scope",
  localOwnerEditAuthorizationCore: "convax.local-owner-edit-authorization-core",
  ownerActualWriteEvidence: "convax.owner-actual-write-evidence",
  ownerCanonicalizerDescriptor: "convax.owner-canonicalizer-descriptor",
  protocolSchemaArtifact: "convax.protocol-schema-artifact",
  protocolSchemaBundleCore: "convax.protocol-schema-bundle-core",
  prunableCheckpointSetCertificateCore: "convax.prunable-checkpoint-set-certificate-core",
  prunableCheckpointSetCertificate: "convax.prunable-checkpoint-set-certificate",
  replicaActorHeadSet: "convax.replica-actor-head-set",
  replicaCausalFloorAckCore: "convax.replica-causal-floor-ack-core",
  replicaCausalFloorAck: "convax.replica-causal-floor-ack",
  replicaCheckpointCore: "convax.replica-checkpoint-core",
  replicaCheckpoint: "convax.replica-checkpoint",
  stableCheckpointSetCore: "convax.stable-checkpoint-set-core",
  stateVector: "convax.state-vector",
  typedIntent: "convax.typed-intent",
  validationArtifactSet: "convax.validation-artifact-set",
  yjsUpdate: "convax.yjs-update",
} as const)
