export const COLLABORATION_PROTOCOL_MAJOR = 2 as const
export const CAUSAL_EDIT_KIND_CODE = 1 as const
export const CAUSAL_EDIT_MAGIC = "CVXCOLL2" as const
export const CAUSAL_EDIT_PREFIX_BYTES = 88 as const

/**
 * Identity of the one current collaboration protocol. `protocolDigest` is the
 * only protocol identity; it is recomputed from this package's own source data
 * by the current protocol descriptor and must equal this anchor.
 */
export const CURRENT_PROTOCOL_IDENTITIES = Object.freeze({
  protocolDigest: "de192e03a7466b631b1cefa50f745e22b1ed997f5ce23cbb9c9aea7e46b73bf5",
  uriProtocolDigest: "9030aecd6902888e5e91532fcc2ec3f1a377e79ae59c092ee80fbbf1a01fac38",
  limitsDigest: "88c018e5289f8b9a359f6ae171aed00885d5fa0913f4a1c36274b35e4cee12f7",
  channelContractDigest: "0fa34e8d93f26e585e6d9baa0ecf0c09a38494d03247b91843e2bca0e93df242",
} as const)

export const PROTOCOL_SCHEMA_ARTIFACTS = Object.freeze([
  Object.freeze({
    artifactDigest: "cb69352106c9fc61d28c6412b22b7efb453cd7b9db5324946c0d978772c54d36",
    format: "convax.canvas-protocol-schema/2",
    name: "canvas-schema",
  }),
  Object.freeze({
    artifactDigest: "357bacba24e9be648f7d280fc474c421a5986c002040899b7f382615e8113e01",
    format: "convax.collaboration-kernel-protocol-schema/2",
    name: "collaboration-kernel",
  }),
  Object.freeze({
    artifactDigest: "ac6605ee974a47be65a02c478e854971cbd54146db147cf943391a0f4f557e45",
    format: "convax.control-plane-protocol-schema/2",
    name: "control-plane",
  }),
  Object.freeze({
    artifactDigest: "38f3d762cfd95a6826758750d3cdb518d900ac0b15b8338aa6dfd58733e9353c",
    format: "convax.project-persistence-protocol-schema/2",
    name: "project-persistence",
  }),
] as const)

export const PROTOCOL_TYPE_NAMESPACES = Object.freeze([
  Object.freeze({ namespace: "canvas-schema", imports: Object.freeze(["collaboration-kernel", "control-plane", "global-uri"] as const) }),
  Object.freeze({ namespace: "collaboration-kernel", imports: Object.freeze(["global-uri"] as const) }),
  Object.freeze({ namespace: "control-plane", imports: Object.freeze(["collaboration-kernel", "global-uri", "project-persistence"] as const) }),
  Object.freeze({ namespace: "global-uri", imports: Object.freeze([] as const) }),
  Object.freeze({ namespace: "project-persistence", imports: Object.freeze(["canvas-schema", "collaboration-kernel", "control-plane", "global-uri"] as const) }),
] as const)

export const YJS_WIRE_CODEC = Object.freeze({
  applyCodec: "Y.applyUpdate",
  format: "convax.yjs-wire-codec/2",
  package: "yjs",
  packageIntegrity: "sha512-Eq+5BRfbeGyqGVrTJL3bEcr8gKkxPuyuoHmAwpk52fDb8kOVMrfVSTRPd6yiGgX5Fskb96qCRjzjbRjrL4YEnw==",
  stateVectorCodec: "Y.encodeStateVector",
  updateCodec: "Y.encodeStateAsUpdate",
  updateVersion: "v1",
  version: "13.6.31",
} as const)

/**
 * Sorted closed set of domain separators admitted by the current protocol. It is
 * package-owned source data and participates in the current protocol digest.
 */
export const PROTOCOL_DIGEST_DOMAIN_REGISTRY = Object.freeze([
  "convax.active-peer-directory-core/2",
  "convax.actual-write-evidence/2",
  "convax.authorization-mutation-core/2",
  "convax.begin-authorization-epoch-core/2",
  "convax.blob-durable-ack-core/2",
  "convax.canonical-state/2",
  "convax.canvas-actual-write-value/2",
  "convax.canvas-containment-slot/2",
  "convax.canvas-creation-group-member-set/2",
  "convax.canvas-data-register/2",
  "convax.canvas-derived-id/2",
  "convax.canvas-edge-identity/2",
  "convax.canvas-effective-child-set/2",
  "convax.canvas-effective-data/2",
  "convax.canvas-effective-plugin/2",
  "convax.canvas-generation-begin/2",
  "convax.canvas-generation-dismissal/2",
  "convax.canvas-generation-lifecycle/2",
  "convax.canvas-generation-recovery-failure/2",
  "convax.canvas-generation-terminal/2",
  "convax.canvas-genesis-core/2",
  "convax.canvas-geometry/2",
  "convax.canvas-group-geometry-plan/2",
  "convax.canvas-history-footprint/2",
  "convax.canvas-history-material/2",
  "convax.canvas-history-materialization/2",
  "convax.canvas-metadata-effective/2",
  "convax.canvas-metadata-slot/2",
  "convax.canvas-node-identity/2",
  "convax.canvas-obstacle-projection/2",
  "convax.canvas-operation-receipt/2",
  "convax.canvas-projected-generation/2",
  "convax.canvas-semantic-guard/2",
  "convax.canvas-semantic-history-root/2",
  "convax.canvas-semantic-history-state/2",
  "convax.causal-context/2",
  "convax.causal-dependency-set/2",
  "convax.causal-edit-core/2",
  "convax.causal-edit-frame-digest/2",
  "convax.causal-edit-signature/2",
  "convax.causal-frontier/2",
  "convax.causal-head-ref/2",
  "convax.checkpoint-content-certificate-core/2",
  "convax.checkpoint-content-certificate/2",
  "convax.checkpoint-validation-carrier-index/2",
  "convax.collaboration-scope-entry-core/2",
  "convax.document-registration-abandonment-core/2",
  "convax.document-registration-claim-core/2",
  "convax.document-scope/2",
  "convax.document-shard-reset-approval-core/2",
  "convax.document-shard-reset-claim-core-digest/2",
  "convax.document-shard-reset-claim-signature/2",
  "convax.document-shard-reset-confirmation-core/2",
  "convax.document-shard-reset-route-cas-core-digest/2",
  "convax.empty-project-index-genesis-attestation-core/2",
  "convax.generation-first-loss-receipt-core/2",
  "convax.local-project-store-record-digest/2",
  "convax.member-credential-core/2",
  "convax.membership-snapshot-core/2",
  "convax.mutation-challenge-core/2",
  "convax.mutation-proof-core/2",
  "convax.mutation-receipt-core/2",
  "convax.native-document-store-key/2",
  "convax.native-object-store-key/2",
  "convax.owner-actual-write-evidence/2",
  "convax.owner-canonicalizer-descriptor/2",
  "convax.peer-channel-contract/2",
  "convax.peer-channel-open-core/2",
  "convax.peer-freshness-ticket-core/2",
  "convax.peer-handshake-core/2",
  "convax.peer-inventory-page-core/2",
  "convax.peer-inventory-root-core/2",
  "convax.peer-message-body/2",
  "convax.peer-message-core/2",
  "convax.peer-ticket-request-core/2",
  "convax.peer-transfer-chunk/2",
  "convax.peer-transfer-manifest-core/2",
  "convax.project-admin-capability-core/2",
  "convax.project-conflict-projection/2",
  "convax.project-content-family-projection/2",
  "convax.project-derived-identity/2",
  "convax.project-entry-location-projection/2",
  "convax.project-file-projection/2",
  "convax.project-index-intent-digest/2",
  "convax.project-index-live-scope-manifest/2",
  "convax.project-index-record-digest/2",
  "convax.project-index-write-value/2",
  "convax.project-reset-approval-core/2",
  "convax.project-reset-confirmation-core/2",
  "convax.project-resource-reference-digest/2",
  "convax.project-route-projection/2",
  "convax.protocol-limits/2",
  "convax.protocol-schema-artifact/2",
  "convax.protocol-schema-bundle-core/2",
  "convax.prunable-checkpoint-set-certificate-core/2",
  "convax.prunable-checkpoint-set-certificate/2",
  "convax.registry-cutoff-coverage-page-core/2",
  "convax.registry-cutoff-coverage-root-core/2",
  "convax.registry-entry-identity/2",
  "convax.registry-entry-set/2",
  "convax.registry-snapshot-core/2",
  "convax.replica-actor-credential-core/2",
  "convax.replica-actor-head-set/2",
  "convax.replica-actor-id/2",
  "convax.replica-causal-floor-ack-core/2",
  "convax.replica-causal-floor-ack/2",
  "convax.replica-checkpoint-core/2",
  "convax.replica-checkpoint/2",
  "convax.replica-durable-ack-core/2",
  "convax.replica-edit-authorization-core/2",
  "convax.replica-id-reservation-receipt-core/2",
  "convax.replica-id-reservation-request-core/2",
  "convax.replica-project-floor-page-core/2",
  "convax.replica-project-floor-root-core/2",
  "convax.service-trust-bundle-core/2",
  "convax.session-challenge-core/2",
  "convax.session-credential-core/2",
  "convax.session-proof-core/2",
  "convax.stable-checkpoint-set-core/2",
  "convax.state-vector/2",
  "convax.target-cutoff-leaf-core/2",
  "convax.team-epoch-rollover-challenge-core/2",
  "convax.team-epoch-rollover-proof-core/2",
  "convax.team-epoch-rollover-receipt-core/2",
  "convax.typed-intent/2",
  "convax.validation-artifact-set/2",
  "convax.yjs-update/2",
] as const)

export const KERNEL_LIMITS = Object.freeze({
  actualWriteEvidenceJcsBytes: 256 * 1024,
  causalContextJcsBytes: 64 * 1024,
  causalDependencyRefs: 256,
  causalEnvelopeBytes: 2 * 1024 * 1024,
  causalFrontierHeads: 256,
  causalHeaderJcsBytes: 64 * 1024,
  checkpointFrontierHeads: 256,
  checkpointParents: 8,
  checkpointSnapshotBytes: 32 * 1024 * 1024,
  changedPaths: 2_048,
  localOutboxBytesPerDocument: 512 * 1024 * 1024,
  localOutboxFramesPerDocument: 4_096,
  localRecoveryBranchBytes: 1024 * 1024 * 1024,
  oneChangedPathUtf8Bytes: 512,
  pendingInboxBytesPerDocument: 256 * 1024 * 1024,
  pendingInboxBytesPerRemoteActor: 32 * 1024 * 1024,
  pendingInboxFramesPerDocument: 4_096,
  pendingInboxFramesPerRemoteActor: 512,
  quarantineBytesPerProject: 128 * 1024 * 1024,
  quarantineObjectsPerProject: 1_024,
  retainedDurableAcksPerFrame: 32,
  stateVectorBytes: 64 * 1024,
  stableSetCertificates: 8,
  typedIntentJcsBytes: 512 * 1024,
  validationArtifactRefs: 64,
  writes: 2_048,
  yjsUpdateBytes: 1024 * 1024,
} as const)

export const KERNEL_DIGEST_DOMAINS = Object.freeze({
  actualWriteEvidence: "convax.actual-write-evidence/2",
  canonicalState: "convax.canonical-state/2",
  causalContext: "convax.causal-context/2",
  causalDependencySet: "convax.causal-dependency-set/2",
  causalEditCore: "convax.causal-edit-core/2",
  causalEditFrameDigest: "convax.causal-edit-frame-digest/2",
  causalEditSignature: "convax.causal-edit-signature/2",
  causalFrontier: "convax.causal-frontier/2",
  causalHeadRef: "convax.causal-head-ref/2",
  checkpointContentCertificateCore: "convax.checkpoint-content-certificate-core/2",
  checkpointContentCertificate: "convax.checkpoint-content-certificate/2",
  documentScope: "convax.document-scope/2",
  ownerActualWriteEvidence: "convax.owner-actual-write-evidence/2",
  ownerCanonicalizerDescriptor: "convax.owner-canonicalizer-descriptor/2",
  protocolSchemaArtifact: "convax.protocol-schema-artifact/2",
  protocolSchemaBundleCore: "convax.protocol-schema-bundle-core/2",
  prunableCheckpointSetCertificateCore: "convax.prunable-checkpoint-set-certificate-core/2",
  prunableCheckpointSetCertificate: "convax.prunable-checkpoint-set-certificate/2",
  replicaActorHeadSet: "convax.replica-actor-head-set/2",
  replicaCausalFloorAckCore: "convax.replica-causal-floor-ack-core/2",
  replicaCausalFloorAck: "convax.replica-causal-floor-ack/2",
  replicaCheckpointCore: "convax.replica-checkpoint-core/2",
  replicaCheckpoint: "convax.replica-checkpoint/2",
  stableCheckpointSetCore: "convax.stable-checkpoint-set-core/2",
  stateVector: "convax.state-vector/2",
  typedIntent: "convax.typed-intent/2",
  validationArtifactSet: "convax.validation-artifact-set/2",
  yjsUpdate: "convax.yjs-update/2",
} as const)
