import { describe, expect, test } from "bun:test"
import { renderPluginApiReference } from "./reference"

describe("Plugin-owned Skill reference generation", () => {
  test("renders an empty Host API section and sorted Plugin tools deterministically", () => {
    const rendered = renderPluginApiReference({
      requiredIds: [],
      optionalIds: [],
      pluginTools: [
        { id: "video.render", summary: "Render video." },
        { id: "asset.inspect", summary: "Inspect an asset.", response: "Asset metadata." },
      ],
    })
    expect(rendered).toContain("This Skill does not call a Convax Host API.")
    expect(rendered.indexOf("`asset.inspect`")).toBeLessThan(rendered.indexOf("`video.render`"))
    expect(rendered).toContain("Generated by @convax/plugin-api. Do not edit.")
    expect(rendered).toBe(
      renderPluginApiReference({
        requiredIds: [],
        optionalIds: [],
        pluginTools: [
          { id: "video.render", summary: "Render video." },
          { id: "asset.inspect", summary: "Inspect an asset.", response: "Asset metadata." },
        ],
      }),
    )
  })

  test("rejects Web-only APIs instead of teaching an Agent an unusable call", () => {
    expect(() =>
      renderPluginApiReference({
        requiredIds: ["agent.prompt"],
        optionalIds: [],
      }),
    ).toThrow("not callable by agent-skill")
  })

})
