import { PLUGIN_API_CATALOG_MAJOR, type PluginApiId, pluginApiCatalog } from "./catalog"
import type { PluginApiDefinition } from "./contracts"
import { parsePluginApiDeclaration } from "./declaration"
import { pluginApiMethodContracts, type PluginApiObjectShape } from "./method-contracts"

/**
 * A concrete Plugin-owned tool description included beside Host APIs in a Skill reference.
 *
 * @public
 */
export interface PluginToolReference {
  readonly id: string
  readonly summary: string
  readonly request?: string
  readonly response?: string
}

/**
 * Input for the deterministic, filesystem-free Plugin-owned Skill API reference renderer.
 *
 * @public
 */
export interface PluginApiReferenceInput {
  readonly requiredIds: readonly PluginApiId[]
  readonly optionalIds: readonly PluginApiId[]
  readonly pluginTools?: readonly PluginToolReference[]
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ")
}

function requireText(value: string, label: string): string {
  const normalized = value.trim()
  if (normalized.length === 0) throw new TypeError(`${label} must not be empty`)
  return normalized
}

function renderMethodShape(shape: { readonly type: "none" } | PluginApiObjectShape): string {
  if (shape.type === "none") return "`none`"
  const fields = [
    ...shape.required.map((name) => `${name} (required)`),
    ...shape.optional.map((name) => `${name} (optional)`),
  ]
  return fields.length === 0
    ? "`{}` (closed object)"
    : `closed object: ${fields.map((field) => `\`${field}\``).join(", ")}`
}

function stableContractJson(value: unknown): string {
  const sort = (entry: unknown): unknown => {
    if (Array.isArray(entry)) return entry.map(sort)
    if (!entry || typeof entry !== "object") return entry
    return Object.fromEntries(
      Object.entries(entry as Record<string, unknown>)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, item]) => [key, sort(item)]),
    )
  }
  return JSON.stringify(sort(value), null, 2)
}

/**
 * Renders the generated Host API reference embedded in a Plugin-owned Skill bundle.
 *
 * @public
 */
export function renderPluginApiReference(input: PluginApiReferenceInput): string {
  const declaration = parsePluginApiDeclaration({
    major: PLUGIN_API_CATALOG_MAJOR,
    required: input.requiredIds,
    optional: input.optionalIds,
  })
  const definitionsById = new Map(pluginApiCatalog.apis.map((definition) => [definition.id, definition]))
  const selected = [
    ...declaration.required.map((id) => ({ id, requirement: "required" as const })),
    ...declaration.optional.map((id) => ({ id, requirement: "optional" as const })),
  ].sort((left, right) => left.id.localeCompare(right.id))

  for (const entry of selected) {
    const definition = definitionsById.get(entry.id)
    if (!definition?.audience.includes("agent-skill")) {
      throw new TypeError(`Plugin API ${entry.id} is not callable by agent-skill`)
    }
  }

  const pluginTools = [...(input.pluginTools ?? [])]
    .map((tool) => {
      if (!/^[A-Za-z][A-Za-z0-9._-]{0,127}$/.test(tool.id)) {
        throw new TypeError(`Plugin tool id is invalid: ${tool.id}`)
      }
      return {
        id: tool.id,
        summary: requireText(tool.summary, `${tool.id} summary`),
        ...(tool.request ? { request: requireText(tool.request, `${tool.id} request`) } : {}),
        ...(tool.response ? { response: requireText(tool.response, `${tool.id} response`) } : {}),
      }
    })
    .sort((left, right) => left.id.localeCompare(right.id))
  if (new Set(pluginTools.map((tool) => tool.id)).size !== pluginTools.length) {
    throw new TypeError("Plugin tool ids must be unique")
  }

  const lines = [
    "<!-- prettier-ignore-start -->",
    "",
    "# Convax capabilities",
    "",
    "<!-- Generated by @convax/plugin-api. Do not edit. -->",
    "",
    `Host API catalog: ${pluginApiCatalog.version}`,
    "",
    "Host API availability is connection-scoped. Required APIs must be available before the workflow starts.",
    "For every optional API, check runtime availability immediately before use and follow its unavailable fallback.",
    "An availability result is not authorization; the Host revalidates grants, scope, context, and active Plugin bytes on every call.",
    "",
  ]

  if (selected.length === 0) {
    lines.push("## Host APIs", "", "This Skill does not call a Convax Host API.", "")
  } else {
    lines.push(
      "## Host APIs",
      "",
      "| API | Requirement | Since | Grant | Scope | Side effect | Completion |",
      "| --- | --- | --- | --- | --- | --- | --- |",
    )
    for (const entry of selected) {
      const definition: PluginApiDefinition<PluginApiId> = definitionsById.get(entry.id)!
      lines.push(
        `| \`${definition.id}\` | ${entry.requirement} | ${definition.since} | ${
          definition.grant ? `\`${definition.grant}\`` : "none"
        } | ${definition.scope} | ${definition.sideEffect} | ${definition.completion} |`,
      )
    }
    lines.push("")
    for (const entry of selected) {
      const definition: PluginApiDefinition<PluginApiId> = definitionsById.get(entry.id)!
      lines.push(
        `### \`${definition.id}\``,
        "",
        definition.docs.summary,
        "",
        definition.docs.description,
        "",
        `- Requirement: ${entry.requirement}`,
        `- Available since: Host API ${definition.since}`,
        `- Required grant: ${definition.grant ? `\`${definition.grant}\`` : "none"}`,
        `- Scope: ${definition.scope}`,
        `- Side effect: ${definition.sideEffect}`,
        `- Completion: ${definition.completion}`,
        `- Request: ${definition.docs.request}`,
        `- Response: ${definition.docs.response}`,
        `- Request schema: ${renderMethodShape(pluginApiMethodContracts[definition.id].params)}`,
        `- Response schema: ${renderMethodShape(pluginApiMethodContracts[definition.id].result)}`,
        `- Request byte limit: ${pluginApiMethodContracts[definition.id].request.maxBytes}`,
        `- Response byte limit: ${pluginApiMethodContracts[definition.id].response.maxBytes}`,
        `- Contract dialect: \`${pluginApiMethodContracts[definition.id].dialect}\``,
      )
      if (definition.docs.remarks) lines.push(`- Remarks: ${definition.docs.remarks}`)
      lines.push(
        "",
        "Request contract:",
        "",
        "```json",
        stableContractJson(pluginApiMethodContracts[definition.id].request),
        "```",
        "",
        "Response contract:",
        "",
        "```json",
        stableContractJson(pluginApiMethodContracts[definition.id].response),
        "```",
      )
      lines.push("", "Stable errors:", "")
      for (const error of definition.errors) {
        lines.push(
          `- \`${error.code}\` (${error.recoverable ? "recoverable" : "not recoverable"}): ${error.description}`,
        )
      }
      lines.push("")
    }
  }

  if (pluginTools.length === 0) {
    lines.push("## Plugin tools", "", "This Skill does not declare a Plugin-owned tool.", "")
  } else {
    lines.push("## Plugin tools", "", "| Tool | Purpose | Request | Response |", "| --- | --- | --- | --- |")
    for (const tool of pluginTools) {
      lines.push(
        `| \`${escapeCell(tool.id)}\` | ${escapeCell(tool.summary)} | ${escapeCell(tool.request ?? "See tool schema.")} | ${escapeCell(tool.response ?? "See tool schema.")} |`,
      )
    }
    lines.push("")
  }

  lines.push("<!-- prettier-ignore-end -->")
  return `${lines.join("\n")}\n`
}
